### ISSUE TITLE
Research : Create proxy server for reliefweb, unhcr

### ISSUE THREAD

**Issue by udaynwa** [the-deep/server#1183]
Need to prevent:
* Auto downloads
* Redirects

Test link: https://reliefweb.int/sites/reliefweb.int/files/resources/UKR_SitRep_No7_final.pdf
Current setup: https://github.com/the-deep/preview-proxy

**Comment by subinasr** [comment]
Duplicate issue: https://github.com/the-deep/client/issues/2649
