### ISSUE TITLE
Word Export: Show selected scale as a badge after excerpt

### ISSUE THREAD

**Issue by AdityaKhatri** [the-deep/server#498]
Find out different options and present it to PO.
We should have it as graphical instead of text.
Not show it for non-selected conditional widgets.

**Comment by AdityaKhatri** [comment]
Spike task.
Take around 6 hours.

**Comment by annshress** [comment]
> Not show it for non-selected conditional widgets.

I would appreciate some elaboration on this.

**Comment by AdityaKhatri** [comment]
@annshress , regarding the conditional widgets.
A conditional widget can have multiple widgets within itself.
It will render the widgets based on set conditions.
We only show the value of the scale widget if the scale widget was the selected widget inside the conditional widget.

**Comment by annshress** [comment]
@Ewan-Oglethorpe @AdityaKhatri 
Last friday, I came across two approaches. One was using the shading, and other was inserting an actual shape into the word document.
Let me know what thoughts you have on this.

PFA [demo document](https://zube.io/files/deep/a1f9fe3df1c4539e8a572fafb84afbf8-demo.docx) depicting the outputs.

If okay, we will also use **selected** approach to provide legends at the beginning of the exporting document.

**Comment by eoglethorpe** [comment]
@Anish, this looks great, thanks!

I think we shoudl go with the circles, but with a grey border instead of a black one? sample image shown. As for the circle colors themselves, can we take colors from the DEEP style guide? lemme know if you need me to send it.


![image.png](https://zube.io/files/deep/4d953b43de4e0ea92e060d39198322de-image.png)

**Comment by eoglethorpe** [comment]
also, could we please put these at the end of a citation? ![image.png](https://zube.io/files/deep/c4e73910010e73792159d46da6afcc8b-image.png)

something like this?

**Comment by anish** [comment]
@eoglethorpe wrong person I think

**Comment by eoglethorpe** [comment]
ha totally. thanks @anish , and sorry :) @annshress...

**Comment by annshress** [comment]
@eoglethorpe 
> As for the circle colors themselves, can we take colors from the DEEP style guide? lemme know if you need me to send it.

Regarding this, we will be using the colors directly from the scale input itself.

**Comment by eoglethorpe** [comment]
good point, thanks @annshress

**Comment by annshress** [comment]
Please check the following attachment.

@eoglethorpe @AdityaKhatri 

[20200930_DEEP_Entries_General_Export_6YKWAQF.docx](https://zube.io/files/deep/a68835476c958425de3e305ce71c9cbd-20200930_deep_entries_general_export_6ykwaqf.docx)
