### ISSUE TITLE
Entries QA: Create consolidated API for geo-options, regions, and framework for entry edit

### ISSUE THREAD

**Issue by AdityaKhatri** [the-deep/server#501]
Look to see if already available

**Comment by tnagorra** [comment]
We need an api to get data for a specific entry, analysis framework, geo-options, regions

**Comment by AdityaKhatri** [comment]
@tnagorra , the edit functionality has already been completed, should we close this issue?

**Comment by AdityaKhatri** [comment]
Decided to create new API
