### ISSUE TITLE
Entries QA: API to fetch count of verified and unverified entries per ToC item

### ISSUE THREAD

**Issue by AdityaKhatri** [the-deep/server#503]

**Comment by thenav56** [comment]
@samshara 
Providing `calculate_count_per_toc_item` to previous API will add `countPerTocItem` attribute to `summary`. Branch: `feature/toc-fixes`

![image.png](https://zube.io/files/deep/db3e8d1bce285cd24f3a8e349f01d618-image.png)

**Comment by thenav56** [comment]
PR: https://github.com/the-deep/server/pull/580
