### ISSUE TITLE
Word Export: Add ability to breakdown sections by sub-sectors

### ISSUE THREAD

**Issue by AdityaKhatri** [the-deep/server#537]

**Comment by AdityaKhatri** [comment]
Figure out whether or not we can do it in the current setting.
What would be required?
Spend 5 hours

**Comment by thenav56** [comment]
@AdityaKhatri 

We can do this but

- We need to update the level structure generation logic.
- Update client reporting structure with sub-sectors.
- Integrate sub-sector level in report export.
- Run widget migration in production.

Will this feature replace the current structure or is an optional mode?
