### ISSUE TITLE
Entries QA: Add summaries for filtered entries in API

### ISSUE THREAD

**Issue by AdityaKhatri** [the-deep/server#540]
Add:
1. Total number of leads
2. Total number of entries
   2.1 verified
   2.2 unverified
3. Number of unique authoring organizations by organization type
4. Number of publishers

**Comment by thenav56** [comment]
@annshress 
Let's append summary data to the list API, something like this
```json
{
    "count": 1000,
    ........
    "summary": {},
   "results": [....],
}
```

Also, add a GET parameter to show/hide summary data. like `calculate_summary` to avoid duplicate computation for paginted responses.
