### ISSUE TITLE
Word export: Add entry details before excerpt

### ISSUE THREAD

**Issue by AdityaKhatri** [the-deep/server#545]
Acceptance criteria:
1. User provides a list of entry details to show before the excerpt
2. Values separated by a comma should be displayed

Support:
1. List widgets
2. Geo widgets (show only admin 1 if present)
3. Date widgets
4. Time widgets
5. Organigram widgets
6. Date range widget
7. Time range widget

**Comment by AdityaKhatri** [comment]
@eoglethorpe , let me know if this is okay for now.

**Comment by AdityaKhatri** [comment]
@eoglethorpe , @jbbove , 
1. what should be the format to separate the values between widgets and values of widgets?
2. Let me know if we should move the scale widget to the start or not?
3. Should we skip the widget with no data or have some indication that the data is missing?

Image provided by Patrice:
![image.png](https://zube.io/files/deep/482c64a5664e5109db0b1d0e75f41855-image.png)

**Comment by eoglethorpe** [comment]
@AdityaKhatri last time we talked we were just going to have a fixed citation structure. have we gone away from that?

1) i'm not sure about this, i'd defer to @Mariam-Asatryan 
2) I would also defer to @Mariam-Asatryan 
3) I think we should just leave them if there's no value

**Comment by AdityaKhatri** [comment]
Hi @eoglethorpe , from my understanding having a fixed citation works for lead data, but we are talking about adding entry's widget data in word export.
My suggestion would be adding flexibility in what you want to see for other entry data for people who want to modify it as we can't really provide suggestions for entry data due to the dynamic nature of the analysis framework.

**Comment by AdityaKhatri** [comment]
[201105_New_entry_export_design_with_context.docx](https://zube.io/files/deep/f9478a67c525c1f0efa4402e7a4f3456-201105_new_entry_export_design_with_context.docx)
