### ISSUE TITLE
Serverless: Move thumbnail generation to Lambda

### ISSUE THREAD

**Issue by AdityaKhatri** [the-deep/server#558]

**Comment by thenav56** [comment]
We were only able to work on headless-chrome.

For non-website (pdf, Docx, ...) files LibreOffice is used right now in the core deep application. Unfortunately after much research, we couldn't find the necessary LibreOffice build required. We could go in-depth about how LibreOffice is built and try to build within our needs but that will be more complex.

For now, we will try to use the google driver viewer to generate thumbnails for non-website documents. But this also can have an issue if google driver viewer changes their structure or throttle our request. So we will need a fallback in core deep. Creating a separate card for this.
