### ISSUE TITLE
Put password character limit to 128

### ISSUE THREAD

**Issue by AdityaKhatri** [the-deep/server#603]
Confirm character limit with Jean

**Comment by AdityaKhatri** [comment]
@jbbove @eoglethorpe also, do we think we need to implement password restrictions/policies?

**Comment by eoglethorpe** [comment]
@AdityaKhatri yeah. @jbbove, could you follow up with boldcode to get their reccomendations?

**Comment by jbbove** [comment]
@Ewan-Oglethorpe I did and Valentin should get back to us with a recommendation
