### ISSUE TITLE
Analysis Module: Create API for analyses stats of a project

### ISSUE THREAD

**Issue by AdityaKhatri** [the-deep/server#659]
![image.png](https://zube.io/files/deep/b2264bb89168053a4a9015263050d7b9-image.png)
Take unique authoring organizations of unique sources that belong to unique analyzed entries used for organization types.

Add timestamp and count of unique entries used in each analysis after each save.
Return the timestamp-count for chart above.
Lets not cache organization types.

**Comment by jbbove** [comment]
Unit= #of entries dragged/dropped + #of entries discarded
