### ISSUE TITLE
Analysis Module: Create analyses list API for a project with extra stats

### ISSUE THREAD

**Issue by AdityaKhatri** [the-deep/server#660]
![image.png](https://zube.io/files/deep/b35dc4f98f69e91c649061ccadb6b607-image.png)

For more details visit:
https://docs.google.com/document/d/17AtUnzeFz1vIxKN_iFizZjLaj78vpfo_/edit
Extra stats to include:
1. Entries analyzed (#entries in the statements columns / #total entries)
2. Count of analytical statements
3. Total entries in the project
4. Total entries used in the analysis

**Comment by jbbove** [comment]
This is set from the project flow: remember an analysis is part of a project, just like the tagging so we keep the same roles and users

**Comment by jbbove** [comment]
Also on the analytical statements tab, it makes more sense to show on the left the name of a sector from the analytical framework, and on the right the number of analytical statements for that specific sector
