### ISSUE TITLE
Pillar Analysis: Handle errors in entry, analytical statement and pillar analysis level

### ISSUE THREAD

**Issue by AdityaKhatri** [the-deep/server#735]
## Acceptance Criteria
- Make sure deleted entries are provided in error.
- Make sure the entries attached belong to the current project.
- Make sure all tests have the correct project assigned to the created objects.

**Comment by k9845** [comment]
This ticket is halted for now, since we have certain error responses. Need to change only if the client-side suggests something new.
@Suraj-Shrestha
