### ISSUE TITLE
Export: Implement citations in footnotes

### ISSUE THREAD

**Issue by AdityaKhatri** [the-deep/server#759]

**Comment by thenav56** [comment]
We have implemented the footnotes using bayoo-docx (python-docx forked). This lacks hyperlink implementation. We have created a new ticket for that https://github.com/the-deep/server/issues/768.

Current progress. Hyperlink doesn't work.
[Preview-20210526_DEEP_Entries_General_Export_HymCMr1.pdf](https://zube.io/files/deep/ceee37fb5ad5510c365155a1342ead77-preview-20210526_deep_entries_general_export_hymcmr1.pdf)
![2021-05-27-092659.png](https://zube.io/files/deep/349000aa0251380aa9c820b7d222ef4b-2021-05-27-092659.png)
