### ISSUE TITLE
The users should be able to only create N widgets and M sections.

### ISSUE THREAD

**Issue by tnagorra** [the-deep/server#853]
* The limits should be decided by the team.
* Excluding soft deleted entities
* where N=50, M=5

NOTE:
We cannot paginate the widgets and sections so we are limiting the total no. of items the users can create.

**Comment by thenav56** [comment]
@Suraj-Shrestha @tnagorra @frozenhelium @AdityaKhatri 

Since we have secondary tagging, should the limit there be 50 as well? And 50 for every 5 sections?

**Comment by thenav56** [comment]
~~We will have.~~
~~50 widgets max. (Af widgets limit)~~
~~5 sections max.~~

**Comment by thenav56** [comment]
We will have this now.
    MAX_SECTIONS_ALLOWED = 5
    MAX_WIDGETS_ALLOWED_PER_SECTION = 10
    MAX_WIDGETS_ALLOWED_IN_SECONDARY_TAGGING = 50

So max widgets will be 5 * 10 + 50 = 100 (AF limit)

**Comment by tnagorra** [comment]
Works for me!
