### ISSUE TITLE
When editing/creating entry, lock all navigations

### ISSUE THREAD

**Issue by suraj-ram-shrestha** [the-deep/server#878]
![Screen Shot 2021-07-26 at 11.44.26 AM.png](https://zube.io/files/deep/b99f406c06b11dd5ea65f832e109a9dc-screen-shot-2021-07-26-at-11-44-26-am.png)

## Acceptance Criteria
* Disable buttons
* Disable all navigation on editing/creating entry (simplified text, orginal, all entries)
* Disable editing/creating other entry

### Attachments
- [Figma Link]()

**Comment by frozenhelium** [comment]
This should be done only after all possible navigation is in place
