### ISSUE TITLE
DEEP Stats: Generate Project Stats for Explore Page

### ISSUE THREAD

**Issue by subinasr** [the-deep/server#990]
**Insert Screenshot**
![image.png](https://zube.io/files/deep/043cbe8c69729e0527c2beab9e9ee798-image.png)

## Acceptance Criteria
- Ignore 'Top 5 most active organizations' for now.
- Should contain the following stats:
    - sources added weekly
    - daily average sources tagged per project
    - generated reports monthly
    - top 5 most active projects
- All these must be cached
### New Addition
- Add total projects count (public and private both)
- Add total users count
### Attachments
- [Figma Link](https://www.figma.com/proto/HaQd4COVlpSMoqSfgL5ZDx/DEEP---UI_Library-%2B-Screens?node-id=10324%3A80896&scaling=min-zoom&hide-ui=1)

**Comment by thenav56** [comment]
Using this for calculating metrics.
```
leads_added_weekly= total lead / (total number of weeks from max(created_at) to min(created_at))
daily_average_leads_tagged_per_project= total tagged lead / (number of days between max(created_at) and min(created_at) / number of projects,
generated_exports_monthly= total exports / (total number of months between max(created_at) and min(created_at)
```
And entries count (last 3 months) for active projects.

Also, all leads/exports are included while calculating (private as well).

cc: @Subina-Sharma-Rajopadhyaya
