### ISSUE TITLE
Map View: Create query for list of centroids along with Projects metadata

### ISSUE THREAD

**Issue by subinasr** [the-deep/server#991]
## Acceptance Criteria
- Calculate the centroid of geo areas of projects and create a list.
- The list should also contain information like project id, project title, whether or not it is private, date of creation, etc

### Attachments
- [Figma Link](https://www.figma.com/proto/HaQd4COVlpSMoqSfgL5ZDx/DEEP---UI_Library-%2B-Screens?node-id=10324%3A80896&scaling=min-zoom&hide-ui=1)

**Comment by thenav56** [comment]
Logic used:
We are calculating the centroid of regions by using admin level 0.
Then we group projects by centroids and list them.
